UsersMainLink_xpath = '//a[text()="Users"]/parent::li'
UsersForApprovalTab_xpath = '//div[text()="Users for Approval"]'
deleteUser_xpath = '(//span[@class="anticon anticon-delete"])[1]'
userDeletedMessage = '//span[text()="User Deleted Successfully"]'
userAddedMessage = '//span[text()="User Added Successfully"]'
userEditBtn_xpath = '(//span[@class="anticon anticon-edit"])[1]'
firstNameInput = '//input[@placeholder="Enter First Name"]'
lastNameInput = '//input[@placeholder="Enter Last Name"]'
phoneNumberInput = '//input[@placeholder="Enter Phone Number"]'
saveChangesButton = '//button[text()="Save Changes"]'
invalidUserMessage = '//span[text()="User Updated Successfully"]'
firstRow = '(//tbody[@class="ant-table-tbody"]//tr[@class="ant-table-row ant-table-row-level-0"])[1]//td[not(' \
           './/label[@class="ant-radio-wrapper"])]'

# Add New User
addNewUserMain_xpath = '//a[text()="Add New User"]'
AddUserButton = '//button[contains(text(),"Add User")]'
phoneInput = '//input[@name="phone"]'
Email_xpath = '//input[@placeholder="Enter Email"]'
roleClickField = '//span[text()="Select User Role"]/parent::div/parent::div'
selectAdmin = '//div[text()="Super Admin"]'
inActiveRadioBtn = '//span[text()="In-active"]/parent::label//input[@type="radio"]'
