UsersMainLink_xpath = '//a[text()="Users"]/parent::li'
UsersForApprovalTab_xpath = '//div[text()="Users for Approval"]'
deleteUser_xpath = '(//span[@class="anticon anticon-delete"])[1]'
userDeletedMessage = '//span[text()="User Deleted Successfully"]'
userEditBtn_xpath = '(//span[@class="anticon anticon-edit"])[1]'
firstNameInput = '//input[@placeholder="Enter First Name"]'
lastNameInput = '//input[@placeholder="Enter Last Name"]'
phoneNumberInput = '//input[@placeholder="Enter Phone Number"]'
saveChangesButton = '//button[text()="Save Changes"]'
invalidUserMessage = '//span[text()="User Updated Successfully"]'
